[package]
name = "foxreq-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[features]
default = []
nss = []
nss-real = [
  "nss",
  "dep:brotli-decompressor",
  "dep:flate2",
  "dep:ruzstd",
]

[dependencies]
brotli-decompressor = { version = "5.0.3", optional = true }
flate2 = { version = "1.1.9", default-features = false, features = ["rust_backend"], optional = true }
ruzstd = { version = "0.8.2", optional = true }

[[example]]
name = "capture_tls"
required-features = ["nss-real"]

[[example]]
name = "https_get"
required-features = ["nss-real"]
