[package]
name = "foxreq-py"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lib]
name = "_foxreq"
crate-type = ["cdylib", "rlib"]

[features]
default = []
extension-module = ["pyo3/extension-module"]

[dependencies]
foxreq-core = { path = "../foxreq-core", features = ["nss-real"] }
pyo3 = { version = "0.29.0", features = ["abi3-py310"] }
